PRAXISNETWORK/PRAXISNETWORK/Models/ProposalApplications.cs
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PRAXISNETWORK.Models
{
    public class ProposalApplications
    {
        public int page { get; set; }

        public int pageSize { get; set; }

        public int proposalId { get; set; }

        public int userId { get; set; }

        public String username { get; set; }

        public String applicationDate { get; set; }

        public List<SelectListItem> status { get; set; }

        public PagedList<ProposalApplications> allProposalApplications()
        {
            Models.PraxisDBEntities db = new Models.PraxisDBEntities();
            List<ProposalApplications> applications = new List<ProposalApplications>();

            var allApplications = from apps in db.Applications
                                  join users in db.Users on apps.userId equals users.id
                                  where apps.proposalId == this.proposalId && apps.userId == this.userId
                                  select new
                                  {

                                      proposalId = apps.proposalId,
                                      userId = apps.userId,
                                      username = users.firstName + " " + users.lastName,
                                      applicationDate = apps.applicationDate,
                                      status = apps.status
                                  };

            if (allApplications.ToList() != null && allApplications.ToList().Count() > 0)
                foreach (var app in allApplications)
                {

                    ProposalApplications proposal = new ProposalApplications();

                    proposal.proposalId = app.proposalId;
                    proposal.userId = app.userId;
                    proposal.username = app.username;
                    proposal.applicationDate = app.applicationDate.Date.ToString("yyyy-MM-dd");
                    proposal.status = new List<SelectListItem>(){

                            new SelectListItem(){Value = Utils.ApplicationStatus.PENDING.ToString() + "," + app.proposalId + "," + app.userId, Text = Utils.ApplicationStatus.PENDING.ToString(), Selected = (app.status.Equals(Utils.ApplicationStatus.PENDING.ToString())? true:false)},
                            new SelectListItem(){Value = Utils.ApplicationStatus.REJECTED.ToString() + "," + app.proposalId + "," + app.userId, Text = Utils.ApplicationStatus.REJECTED.ToString(), Selected = (app.status.Equals(Utils.ApplicationStatus.REJECTED.ToString())? true:false)},
                            new SelectListItem(){Value = Utils.ApplicationStatus.ASSIGNED.ToString() + "," + app.proposalId + "," + app.userId, Text = Utils.ApplicationStatus.ASSIGNED.ToString(), Selected = (app.status.Equals(Utils.ApplicationStatus.ASSIGNED.ToString())? true:false)}
                        };

                    applications.Add(proposal);
                }

            return new PagedList<ProposalApplications>(applications, this.page, this.pageSize);
        }
    }
}

PRAXISNETWORK/PRAXISNETWORK/Controllers/ApplicationController.cs
using PagedList;
using PRAXISNETWORK.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PRAXISNETWORK.Controllers
{
    /// <summary>
    /// Handles all web requests concerned with the proposal´s offer applications
    /// </summary>
    public class ApplicationController : Controller
    {
        /// <summary>
        /// Shows the a student´s application information for a proposal´s offer
        /// </summary>
        /// <param name="proposalId">Proposal´s identification number</param>
        /// <param name="userId">Student´s identification number</param>
        /// <returns>Html page with the user´s application infromation</returns>
        public ActionResult ShowApplication(int proposalId, int userId)
        {
            if (Session["userId"] != null && (int)Session["userType"] == 1)
            {
                PraxisDBEntities db = new PraxisDBEntities();
                ModelViews.Application.ApplicationShow appShow = new ModelViews.Application.ApplicationShow();

                IEnumerable<Application> applications = from apps in db.Applications
                                                        where apps.proposalId == proposalId
                                                        select apps;

                IEnumerable<ApplicationDocs> applicationDocs = from appDocs in db.ApplicationDocs
                                                               where appDocs.proposalId == proposalId && appDocs.userId == userId
                                                               select appDocs;

                IEnumerable<User> users = from usrs in db.Users
                                          where usrs.id == userId
                                          select usrs;

                Application application = null;
                User user = null;

                try
                {
                    application = applications.FirstOrDefault();
                }
                catch (NullReferenceException ex)
                {
                    ViewBag.Error = "Occurred an error while acessing proposal´s application...Please try again or contact the administrator.";
                    Utils.writeLog("[Controller: " + RouteData.Values["controller"].ToString() + "]\n[Action method: " + RouteData.Values["action"].ToString() + "]\n[Error: " + ViewBag.Error + "]\n[Exception message:\n\n" + ex.InnerException.Message + "]");
                    return View("ApplicationResponse");
                }

                try
                {
                    user = users.FirstOrDefault();
                }
                catch (NullReferenceException ex)
                {
                    ViewBag.Error = "Occurred an error while acessing application user information...Please try again or contact the administrator.";
                    Utils.writeLog("[Controller: " + RouteData.Values["controller"].ToString() + "]\n[Action method: " + RouteData.Values["action"].ToString() + "]\n[Error: " + ViewBag.Error + "]\n[Exception message:\n\n" + ex.InnerException.Message + "]");
                    return View("ApplicationResponse");
                }

                appShow.username = user.firstName + " " + user.lastName;
                appShow.proposalId = application.proposalId;
                appShow.userId = application.userId;
                appShow.message = application.message;
                appShow.docs = applicationDocs.ToList();

                ViewBag.Title = "Application information";

                return View(appShow);
            }
            else
            {

                return RedirectToAction("Index", "Login");
            }
            return null;
        }

        /// <summary>
        /// Shows a student´s information
        /// </summary>
        /// <param name="applicantId">Student´s identification number</param>
        /// <returns>Html page about student´s information</returns>
        public ActionResult ShowApplicant(int applicantId)
        {

            if (Session["userId"] != null && (int)Session["userType"] == 1)
            {

                PraxisDBEntities db = new PraxisDBEntities();
                ModelViews.Application.ApplicantShow applicant = new ModelViews.Application.ApplicantShow();

                IEnumerable<User> users = from usrs in db.Users
                                          where usrs.id == applicantId
                                          select usrs;

                User user = null;

                try
                {
                    user = users.FirstOrDefault();
                }
                catch (NullReferenceException ex)
                {
                    ViewBag.Error = "Occurred an error trying to access the applicant information...Please try again or contact the adminsitrator.";
                    Utils.writeLog("[Controller: " + RouteData.Values["controller"].ToString() + "]\n[Action method: " + RouteData.Values["action"].ToString() + "]\n[Error: " + ViewBag.Error + "]\n[Exception message:\n\n" + ex.InnerException.Message + "]");
                    return View("ApplicationResponse");
                }

                applicant.about = user.about;
                applicant.birthDate = user.birthDate;
                applicant.gender = user.gender;
                applicant.email = user.email;
                applicant.id = user.id;
                applicant.name = user.firstName + " " + user.lastName;
                applicant.picture = user.picture;

                if (user.cityId != null)
                {
                    var citiesAndCountries = from cities in db.Cities
                                             join countries in db.Countries on cities.countryId equals countries.id
                                             where cities.id == user.cityId
                                             select new
                                             {

                                                 countryName = countries.name,
                                                 cityname = cities.name
                                             };

                    try
                    {
                        applicant.city = citiesAndCountries.FirstOrDefault().cityname;
                        applicant.country = citiesAndCountries.FirstOrDefault().countryName;
                    }
                    catch (NullReferenceException ex)
                    {
                        ViewBag.Error = "Occurred an error trying to access the applicant´s city and country information...Please try again or contact the adminsitrator.";
                        Utils.writeLog("[Controller: " + RouteData.Values["controller"].ToString() + "]\n[Action method: " + RouteData.Values["action"].ToString() + "]\n[Error: " + ViewBag.Error + "]\n[Exception message:\n\n" + ex.InnerException.Message + "]");
                        return View("ApplicationResponse");
                    }
                }

                ViewBag.Title = "Applicant information";

                return View(applicant);

            }
            else
            {

                return RedirectToAction("Index", "Login");
            }
        }

        /// <summary>
        /// Shows all applications made for the a specific proposal´s offer
        /// </summary>
        /// <param name="proposalId">Proposal´s offer identification number</param>
        /// <param name="page">Pagination´s page number</param>
        /// <param name="pageSize">Pagination´s number of applications per page</param>
        /// <returns>Html page with all applications for a specific proposal´s offer</returns>
        public ActionResult ProposalApplications(int proposalId, int page = 1, int pageSize = 5)
        {
            if (Session["userId"] != null && (int)Session["userType"] == 1)
            {
                Models.PraxisDBEntities db = new Models.PraxisDBEntities();

                IEnumerable<Models.Proposal> proposals = from props in db.Proposals
                                                         where props.id == proposalId
                                                         select props;

                Models.ProposalApplications applications = new Models.ProposalApplications();
                applications.page = page;
                applications.pageSize = pageSize;
                applications.proposalId = proposalId;

                ViewBag.Title = "\"" + proposals.FirstOrDefault().title + "\" - Proposal´s applications";

                return View(applications);
            }
            else
            {
                return RedirectToAction("Index", "Login");
            }
        }

        /// <summary>
        /// Shows form fields to apply to a specific proposal´s offer
        /// </summary>
        /// <param name="id">Proposal´s offer identification number</param>
        /// <returns>Html page to fill the information required for the proposal´s offer</returns>
        public ActionResult ApplyOffer(int id = 0)
        {
            // Tests if the user is authenticated
            if (Session["userId"] != null)
            {

                // Tests if user is a student
                if ((int)Session["userType"] == 2)
                {
                    ModelViews.Application.Application application = new ModelViews.Application.Application();
                    application.proposalId = id;
                    application.userId = (int)Session["userId"];

                    ViewBag.Title = "Offer application";

                    return View(application);
                }
                else
                {
                    Session.Clear();
                    Session.Abandon();
                    return RedirectToAction("Index", "Login");
                }


            }
            else
            {

PRAXISNETWORK/PRAXISNETWORK/Views/Application/ApplicationResponse.cshtml
@{
    Layout = "~/Views/Shared/_Master.cshtml";
}

@section title{

    @ViewBag.Title
}

<div class="container-fluid">
    <div class="row">
        <div class="col-md-10 col-md-offset-1">
            <div>
                <h1>@ViewBag.Title</h1>
            </div>
            <br />
            @if (ViewBag.Success != null)
            {

                <div class="alert alert-success" role="alert">@ViewBag.Success</div>
            }
            else if (ViewBag.Error != null)
            {

                <div class="alert alert-danger" role="alert">@ViewBag.Error</div>
            }
        </div>
    </div>
</div>

PRAXISNETWORK/PRAXISNETWORK/Views/Application/ApplyOffer.cshtml
@model PRAXISNETWORK.ModelViews.Application.Application

@{
    Layout = "~/Views/Shared/_Master.cshtml";
}

@section title{
    @ViewBag.Title
}

@section header{
    <script src="~/Scripts/Application/ApplyOffer.js"></script>
}

<div class="container">
    <div class="row">
        <div class="col-md-10 col-md-offset-1">
            @using (Html.BeginForm("SaveApplication", "Application", FormMethod.Post, new { enctype = "multipart/form-data" }))
            {

                @Html.AntiForgeryToken()

                <h1>@ViewBag.Title</h1>
                <br />
                <hr />
                @Html.HiddenFor(model => model.proposalId, Model.proposalId)
                @Html.HiddenFor(model => model.userId, Model.userId)
                <div class="form-group">
                    @Html.LabelFor(model => model.docsUploaded)
                    <div id="files">
                        <div>
                            <input type="file" name="docsUploaded" id="docsUploaded" />
                        </div>
                    </div>
                    <div>
                        <input type="button" value="Add another document" id="newDoc" class="btn btn-sm" /><br />
                        <input type="button" value="Remove a document" id="removeDoc" class="btn btn-sm" style="display: none" />
                    </div>
                    <br />
                    @Html.ValidationMessageFor(model => model.docsUploaded)
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.message)<br />
                    @Html.EditorFor(model => model.message)
                </div>
                <div>
                    <hr />
                    <input type="submit" value="SAVE APPLICATION" class="btn btn-warning" />
                </div>
            }
        </div>
    </div>
</div>

PRAXISNETWORK/PRAXISNETWORK/Views/Application/EditOfferApplication.cshtml
@model PRAXISNETWORK.ModelViews.Application.Application

@{
    Layout = "~/Views/Shared/_Master.cshtml";
}

@section title{
    @ViewBag.Title
}

@section header{
    <script src="~/Scripts/Application/EditOfferApplication.js"></script>
}

<div class="container">
    <div class="row">
        <div class="col-md-10 col-md-offset-1">
            @using (Html.BeginForm("UpdateApplication", "Application", FormMethod.Post))
            {

                @Html.AntiForgeryToken()

                <h1>@ViewBag.Title</h1>
                <br />
                <hr />
                @Html.HiddenFor(model => model.proposalId, Model.proposalId)
                @Html.HiddenFor(model => model.userId, Model.userId)

                <div class="form-group">
                    @Html.LabelFor(model => model.message)<br />
                    @Html.EditorFor(model => model.message)
                </div>
                <div>
                    <input type="submit" value="SAVE APPLICATION" class="btn btn-warning" />
                    <hr />
                </div><br />
                <div style="width: 100%">
                    <div class="panel panel-default">
                        <!-- Default panel contents -->
                        <div class="panel-heading"><b>DOCUMENTS OF THE CURRENT APPLICATION</b></div>
                    </div>
                    <!-- Table -->
                    <div id="docs">
                        @if (ViewBag.Error != null)
                        {

                            @ViewBag.Error
                        }
                        else
                        {
                            <table class="table table-condensed table-bordered table-hover" id="tableDocs">
                                @if (Model.docs.Count() == 0)
                                {
                                    <tr>
                                        <td><b>There´s no documents for the current application...</b></td>
                                    </tr>
                                }
                                else
                                {
                                    <thead>
                                    <th>IDENTIFICATION</th>
                                    <th>SUBMITION DATE</th>
                                    <th>FILE NAME</th>
                                    <th>ACTION</th>
                                    </thead>

                                    foreach (var doc in Model.docs.OrderBy(d => d.submitDate))
                                    {
                                        <tr>
                                            @if (@doc.path.IndexOf(".jpg", StringComparison.OrdinalIgnoreCase) != -1 || @doc.path.IndexOf(".jpeg", StringComparison.OrdinalIgnoreCase) != -1 || @doc.path.IndexOf(".tif", StringComparison.OrdinalIgnoreCase) != -1 || @doc.path.IndexOf(".gif", StringComparison.OrdinalIgnoreCase) != -1)
                                            {
                                                <td><a class="fancybox_image" href="@Url.Content(@doc.path)">@doc.id</a></td>
                                                <td><a class="fancybox_image" href="@Url.Content(@doc.path)">@doc.submitDate.Date.ToString("yyyy-MM-dd")</a></td>
                                                <td><a class="fancybox_image" href="@Url.Content(@doc.path)">@doc.path.Split(System.IO.Path.DirectorySeparatorChar).Last()</a></td>
                                                <td>@Html.ActionLink("Delete", "DeleteApplicationDocument", "Application", new { @docId = doc.id, @proposalId = Model.proposalId }, new { @class = "btn btn-default" })</td>
                                            }
                                            else
                                            {
                                                <td><a class="fancybox_doc" href="@Url.Content(@doc.path)">@doc.id</a></td>
                                                <td><a class="fancybox_doc" href="@Url.Content(@doc.path)">@doc.submitDate.Date.ToString("yyyy-MM-dd")</a></td>
                                                <td><a class="fancybox_doc" href="@Url.Content(@doc.path)">@doc.path.Split(System.IO.Path.DirectorySeparatorChar).Last()</a></td>
                                                <td>@Html.ActionLink("Delete", "DeleteApplicationDocument", "Application", new { @docId = doc.id, @proposalId = Model.proposalId }, new { @class = "btn btn-default" })</td>
                                            }
                                        </tr>
                                    }
                                }
                            </table>
                        }
                    </div>
                </div>
            }

            @if (Model.docs.Count() < 5)
            {

                using (Ajax.BeginForm("AddApplicationDocument", "Application", new { proposalId = Model.proposalId }, new AjaxOptions { HttpMethod = "post" }, new { enctype = "multipart/form-data" }))
                {
                    @Html.AntiForgeryToken()
                    <form name="uploadForm" if="uploadForm" enctype="multipart/form-data">
                        <div class="form-group">
                            @Html.LabelFor(model => model.docsUploaded)
                            <div id="files">
                                <div>
                                    <input type="file" name="docsUploaded" id="docsUploaded" /><button type="submit" class="btn btn-primary" id="fileUpload">UPLOAD FILE</button> (Files with same name will not be saved)
                                    <br />
                                    <div id="errorMessage">

                                    </div>
                                </div>
                            </div>
                        </div>
                    </form>
                }
            }
            <hr />
        </div>
    </div>
</div>

PRAXISNETWORK/PRAXISNETWORK/Views/Application/ProposalApplications.cshtml
@model PRAXISNETWORK.Models.ProposalApplications
@using PagedList.Mvc

@{
    Layout = "~/Views/Shared/_Master.cshtml";
    int dropNumber = 0;
}

@section title{

    @ViewBag.Title
}

@section header{
    <script src="~/Scripts/Proposals/ProposalApplicationsView.js"></script>
}

<div class="container">
    <div class="row">
        <div class="col-md-10 col-md-offset-1">
            <h2>@ViewBag.Title</h2>
            <br />
            <hr />
            <div id="applications">
                <table class="table table-bordered table-hover">
                    @if (Model.allProposalApplications().Count() == 0)
                    {
                        <tr>
                            <td><b>There´s no applications to this proposal...</b></td>
                        </tr>
                    }
                    else
                    {
                        <thead>
                        <th><b>USER´S NAME</b></th>
                        <th><b>APPLICATION DATE</b></th>
                        <th><b>CURRENT STATUS</b></th>
                        <th><b>ACTION</b></th>
                        </thead>
                        foreach (var app in Model.allProposalApplications())
                        {

                            <tr>
                                <td>@Html.ActionLink(@app.username, "ShowApplicant", "Application", new { @applicantId = app.userId }, null)</td>
                                <td>@app.applicationDate</td>
                                <td>@Html.DropDownList("drop_" + @dropNumber, app.status, new { @onchange = "ChangeApplicationStatus("+ (@dropNumber++) +")" })</td>
                                <td>@Html.ActionLink("Show application...", "ShowApplication", "Application", new { @proposalId = app.proposalId, @userId = app.userId }, new { @class = "btn btn-default" })</td>
                            </tr>
                        }
                    }
                </table>
            </div>
            <div class="center-block">
                @Html.PagedListPager(Model.allProposalApplications(), page => Url.Action("ProposalApplications", "Application", new { page, pageSize = Model.pageSize }))
                <b>Showing @Model.allProposalApplications().FirstItemOnPage to @Model.allProposalApplications().LastItemOnPage of @Model.allProposalApplications().TotalItemCount projects/internships</b>
            </div>
            <hr />
        </div>
    </div>
</div>

PRAXISNETWORK/PRAXISNETWORK/Views/Application/ProposalApplicationsPartialView.cshtml
@model PRAXISNETWORK.Models.ProposalApplications

@{
    int dropNumber = 0;
}

<table class="table table-bordered table-hover">
    @if (Model.allProposalApplications().Count() == 0)
    {
        <tr>
            <td><b>There´s no applications to this proposal...</b></td>
        </tr>
    }
    else
    {
        <thead>
        <th><b>USER´S NAME</b></th>
        <th><b>APPLICATION DATE</b></th>
        <th><b>CURRENT STATUS</b></th>
        <th><b>ACTION</b></th>
        </thead>
        foreach (var app in Model.allProposalApplications())
        {

            <tr>
                <td>@Html.ActionLink(@app.username, "ShowApplicant", "Application", new { @Id = app.userId }, null)</td>
                <td>@app.applicationDate</td>
                <td>@Html.DropDownList("drop_" + @dropNumber, app.status, new { @onchange = "ChangeApplicationStatus(" + (@dropNumber++) + ")" })</td>
                <td>@Html.ActionLink("Show application...", "ShowApplication", "Application", new { @proposalId = app.proposalId, @userId = app.userId }, new { @class = "btn btn-default" })</td>
            </tr>
        }
    }
</table>

PRAXISNETWORK/PRAXISNETWORK/Views/Application/ShowApplicant.cshtml
@model PRAXISNETWORK.ModelViews.Application.ApplicantShow

@{
    Layout = "~/Views/Shared/_Master.cshtml";
}

@section title{
    @ViewBag.Title
}

@section header{
    <script src="~/Scripts/Application/ShowApplicant.js"></script>
}

<div class="container">
    <div class="row">
        <div class="col-md-10 col-md-offset-1">
            <h2>PROFILE: @Model.name</h2>
            <br />
            <hr />
            <div class="form-group">
                @Html.Label("Email:")
                <i>@Html.DisplayFor(model => model.email)</i>
            </div>

            <div class="form-group">
                @Html.Label("Gender:")
                <i>@Html.DisplayFor(model => model.gender)</i>
            </div>

            <div class="form-group">
                @Html.Label("Birth date:")
                <i>@Html.DisplayFor(model => model.birthDate)</i>
            </div>

            <div class="form-group">
                @Html.Label("City / Country:")
                <i>@Html.DisplayFor(model => model.city) / @Html.DisplayFor(model => model.country)</i>
            </div>

            <div class="form-group">
                @Html.Label("Some personal information:")
                <i>@Html.DisplayFor(model => model.about)</i>
            </div>

            <div class="form-group">
                @Html.Label("Profile photo:")
                <a class="fancybox_image btn btn-default" href="@Url.Content(@Model.picture)" role="button">Click to show...</a>
            </div>
            <hr />
        </div>
    </div>
</div>

PRAXISNETWORK/PRAXISNETWORK/Views/Application/ShowApplication.cshtml
@model PRAXISNETWORK.ModelViews.Application.ApplicationShow

@{
    Layout = "~/Views/Shared/_Master.cshtml";
}

@section title{
    @ViewBag.Title
}

@section header{
    <script src="~/Scripts/Application/ApplicationShow.js"></script>
}

<div class="container">
    <div class="row">
        <div class="col-md-10 col-md-offset-1">


            <h1>Application made by @Html.ActionLink(Model.username, "ShowApplicant", "Application", new { @applicantId = Model.userId }, null)</h1>
            @Html.HiddenFor(model => model.proposalId, Model.proposalId)
            @Html.HiddenFor(model => model.userId, Model.userId)
            <br />
            <hr />
            <div class="form-group">
                @Html.Label("Applicant message:")<br />
                <i>@Html.DisplayFor(model => model.message)</i>
            </div>
            <br />
            <div style="width: 100%">
                <div class="panel panel-default">
                    <!-- Default panel contents -->
                    <div class="panel-heading"><b>DOCUMENTS OF THE CURRENT APPLICATION</b></div>
                </div>
                <!-- Table -->
                <div>
                    <table class="table table-condensed table-bordered table-hover" id="tableDocs">
                        @if (Model.docs.Count() == 0)
                        {
                            <tr>
                                <td><b>There´s no documents for the current application...</b></td>
                            </tr>
                        }
                        else
                        {
                            <thead>
                            <th>IDENTIFICATION</th>
                            <th>SUBMITION DATE</th>
                            <th>FILE NAME</th>
                            </thead>

                            foreach (var doc in Model.docs.OrderBy(d => d.submitDate))
                            {
                                <tr>
                                    @if (@doc.path.IndexOf(".jpg", StringComparison.OrdinalIgnoreCase) != -1 || @doc.path.IndexOf(".jpeg", StringComparison.OrdinalIgnoreCase) != -1 || @doc.path.IndexOf(".tif", StringComparison.OrdinalIgnoreCase) != -1 || @doc.path.IndexOf(".gif", StringComparison.OrdinalIgnoreCase) != -1)
                                    {
                                        <td><a class="fancybox_image" href="@Url.Content(@doc.path)">@doc.id</a></td>
                                        <td><a class="fancybox_image" href="@Url.Content(@doc.path)">@doc.submitDate.Date.ToString("yyyy-MM-dd")</a></td>
                                        <td><a class="fancybox_image" href="@Url.Content(@doc.path)">@doc.path.Split(System.IO.Path.DirectorySeparatorChar).Last()</a></td>
                                    }
                                    else
                                    {
                                        <td><a class="fancybox_doc" href="@Url.Content(@doc.path)">@doc.id</a></td>
                                        <td><a class="fancybox_doc" href="@Url.Content(@doc.path)">@doc.submitDate.Date.ToString("yyyy-MM-dd")</a></td>
                                        <td><a class="fancybox_doc" href="@Url.Content(@doc.path)">@doc.path.Split(System.IO.Path.DirectorySeparatorChar).Last()</a></td>
                                    }
                                </tr>
                            }
                        }
                    </table>

                </div>
            </div>
            <hr />
        </div>
    </div>
</div>