PRAXISNETWORK/PRAXISNETWORK/Controllers/AdministratorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PRAXISNETWORK.Controllers
{
    /// <summary>
    /// Handles administrator´s requests
    /// </summary>
    public class AdministratorController : Controller
    {
        /// <summary>
        /// Shows administrator´s management borad
        /// </summary>
        /// <returns></returns>
        public ActionResult Index()
        {
            if (Session["userId"] != null && (int)Session["userType"] == 3)
            {

                ViewBag.Title = "Administrator board";

                return View();
            }
            else
            {
                return RedirectToAction("AdminAuthentication", "Login");
            }
        }

        public ActionResult ProviderProposals(int providerId, int page = 1, int pageSize = 5)
        {
            if (Session["userId"] != null && (int)Session["userType"] == 3)
            {

                ViewBag.Title = "Provider proposals";
                Models.ProviderProposals providerProps = new Models.ProviderProposals()
                {

                    userId = providerId,
                    page = page,
                    pageSize = pageSize
                };

                return View(providerProps);
            }
            else
            {
                return RedirectToAction("AdminLogin", "Login");
            }
        }

        public ActionResult StudentProposals(int studentId, int page = 1, int pageSize = 5)
        {
            if (Session["userId"] != null && (int)Session["userType"] == 3)
            {

                ViewBag.Title = "Student proposals applications";
                Models.StudentApplications studentApps = new Models.StudentApplications()
                {

                    userId = studentId,
                    page = page,
                    pageSize = pageSize
                };

                return View(studentApps);
            }
            else
            {
                return RedirectToAction("AdminLogin", "Login");
            }
        }
    }
}

PRAXISNETWORK/PRAXISNETWORK/Controllers/ProviderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PRAXISNETWORK.Controllers
{
    /// <summary>
    /// Handles all requests of an authenticated provider
    /// </summary>
    public class ProviderController : Controller
    {
        /// <summary>
        /// Shows main board of management for the provider
        /// </summary>
        /// <returns>Html page with management board</returns>
        public ActionResult Index()
        {
            if (Session["userId"] != null && (int)Session["userType"] == 1)
            {

                ViewBag.Title = "Provider board";

                return View();
            }
            else
            {
                return RedirectToAction("Index", "Login");
            }
        }

        /// <summary>
        /// Shows all proposals´ offers made by the provider
        /// </summary>
        /// <param name="page">Pagination´s page number</param>
        /// <param name="pageSize">Pagination´s number of proposals to display by page</param>
        /// <returns>Html page with all proposals offers</returns>
        public ActionResult ProviderProposals(int page = 1, int pageSize = 5)
        {
            if (Session["userId"] != null && (int)Session["userType"] == 1)
            {

                int userId = (int)Session["userID"];


                ViewBag.Title = "Your proposals";
                Models.ProviderProposals providerProps = new Models.ProviderProposals()
                {

                    userId = userId,
                    page = page,
                    pageSize = pageSize
                };

                return View(providerProps);
            }
            else
            {
                return RedirectToAction("Index", "Login");
            }
        }

    }
}

PRAXISNETWORK/PRAXISNETWORK/Controllers/RegisterController.cs
using PRAXISNETWORK.Models;
using PRAXISNETWORK.ModelViews.Register;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Security.Cryptography;
using System.Web;
using System.Web.Mvc;

namespace PRAXISNETWORK.Controllers
{
    /// <summary>
    /// Handles all requests concerned with the user´s profile data
    /// </summary>
    public class RegisterController : Controller
    {
        /// <summary>
        /// Shows html page to choose between student and provider registration
        /// </summary>
        /// <returns>Html page</returns>
        public ActionResult Index()
        {
            ViewBag.Title = "Registration";

            return View();
        }

        /// <summary>
        /// Shows html page to fill the student´s data registration
        /// </summary>
        /// <returns>Html page</returns>
        public ActionResult Student()
        {
            ModelViews.Register.Applicant student = new ModelViews.Register.Applicant();
            ViewBag.Title = "Student registration";

            return View(student);
        }

        /// <summary>
        /// Shows html page to edit student´s data registration
        /// </summary>
        /// <returns>Html page</returns>
        public ActionResult StudentEdition()
        {
            if (Session["userId"] != null && (int)Session["userType"] == 2)
            {

                int userId = (int)Session["userId"];
                PraxisDBEntities db = new PraxisDBEntities();
                ModelViews.Register.Applicant student;
                ViewBag.Title = "Student edition";

                IEnumerable<User> users = from usrs in db.Users
                                          where usrs.id == userId
                                          select usrs;

                User user;

                try
                {
                    user = users.FirstOrDefault();
                }
                catch (NullReferenceException ex)
                {
                    ViewBag.Error = "Occurred an error while accessing your profile...Please try again or contact the administrator...";
                    Utils.writeLog("[Controller: " + RouteData.Values["controller"].ToString() + "]\n[Action method: " + RouteData.Values["action"].ToString() + "]\n[Error: " + ViewBag.Error + "]\n[Exception message:\n\n" + ex.InnerException.Message + "]");
                    return View("RegisterResponse");
                }

                var countriesAndCities = from cts in db.Cities
                                         join ctrs in db.Countries on cts.countryId equals ctrs.id
                                         where cts.id == user.cityId
                                         select new
                                         {
                                             countryId = ctrs.id,
                                             cityId = cts.id,
                                         };
                try
                {
                    student = new ModelViews.Register.Applicant
                    {

                        about = user.about,
                        birthDate = user.birthDate,
                        city = (user.city == null ? null : Convert.ToString(countriesAndCities.FirstOrDefault().cityId)),
                        country = (user.city == null ? null : Convert.ToString(countriesAndCities.FirstOrDefault().countryId)),
                        email = user.email,
                        firstName = user.firstName,
                        gender = user.gender,
                        lastName = user.lastName,
                        picturePath = user.picture,
                        username = user.username
                    };
                }
                catch (NullReferenceException ex)
                {
                    ViewBag.Error = "Occurred an error while delivering your profile...Please try again or contact the administrator...";
                    Utils.writeLog("[Controller: " + RouteData.Values["controller"].ToString() + "]\n[Action method: " + RouteData.Values["action"].ToString() + "]\n[Error: " + ViewBag.Error + "]\n[Exception message:\n\n" + ex.InnerException.Message + "]");
                    return View("RegisterResponse");
                }


                return View("StudentEdition", student);
            }
            else
            {
                return RedirectToAction("Index", "Login");
            }
        }

        /// <summary>
        /// Saves new student´s registration
        /// </summary>
        /// <param name="student">Model object with all student´s new data registration</param>
        /// <returns>Html page with process´ result</returns>
        public ActionResult SaveStudent(Applicant student)
        {
            if (ModelState.IsValid)
            {
                PraxisDBEntities db = new PraxisDBEntities();
                User studentRecord = new User();

                ViewBag.Title = "Register result";

                // HANDLE FILE UPLOAD
                if (student.picture != null && student.picture.ContentLength > 0)
                {
                    String dateTime = (DateTime.Now.Date + "_" + DateTime.Now.TimeOfDay).Replace(":", "_");
                    String fileName = Path.GetFileName(student.picture.FileName);
                    String relativePath = "~/Files/UsersPictures/" + dateTime + "_" + fileName;
                    String destinyPath = Server.MapPath(relativePath);

                    try
                    {
                        student.picture.SaveAs(destinyPath);
                    }
                    catch (Exception ex)
                    {
                        ViewBag.Error = "Occurred an error while saving your photo! Please try again or contact the adminsitrator.";
                        Utils.writeLog("[Controller: " + RouteData.Values["controller"].ToString() + "]\n[Action method: " + RouteData.Values["action"].ToString() + "]\n[Error: " + ViewBag.Error + "]\n[Exception message:\n\n" + ex.InnerException.Message + "]");
                        return View("RegisterResponse");
                    }

                    studentRecord.picture = relativePath;

                }

                studentRecord.username = student.username;
                studentRecord.firstName = student.firstName;
                studentRecord.lastName = student.lastName;
                studentRecord.gender = student.gender;
                studentRecord.birthDate = student.birthDate;
                studentRecord.email = student.email;
                studentRecord.password = Utils.encrypt(student.password);
                studentRecord.enabled = true;
                studentRecord.locked = false;
                studentRecord.userTypeId = 2;
                studentRecord.lastLogin = DateTime.Now;

                if (student.about != null)
                    studentRecord.about = student.about;

                if (student.city != "null city")
                    studentRecord.cityId = Convert.ToInt32(student.city);
                else studentRecord.cityId = null;

                db.Users.Add(studentRecord);

                try
                {
                    db.SaveChanges();
                }
                catch (Exception ex)
                {
                    ViewBag.Error = "Occurred an error while saving your registration! Please try again or contact the adminsitrator.";
                    Utils.writeLog("[Controller: " + RouteData.Values["controller"].ToString() + "]\n[Action method: " + RouteData.Values["action"].ToString() + "]\n[Error: " + ViewBag.Error + "]\n[Exception message:\n\n" + ex.InnerException.Message + "]");
                    return View("RegisterReponse");
                }

                ViewBag.Success = "NEW STUDENT RECORD SAVED!!!";

                return View("RegisterResponse");
            }

            return View("Student", student);
        }

        /// <summary>
        /// Saves the edited information of a student´s registration
        /// </summary>
        /// <param name="student">Model object of the student´s data registration</param>
        /// <returns>Html page with process´ result</returns>
        public ActionResult UpdateStudent(Applicant student)
        {
            if (Session["userId"] != null && (int)Session["userType"] == 2)
            {
                if (ModelState.IsValidField("firstName") &&
                    ModelState.IsValidField("lastName") &&
                    ModelState.IsValidField("gender") &&
                    ModelState.IsValidField("birthDate") &&
                    ModelState.IsValidField("about") &&
                    ModelState.IsValidField("password") &&
                    ModelState.IsValidField("passwordConfirmation") &&
                    ModelState.IsValidField("picture"))
                {
                    PraxisDBEntities db = new PraxisDBEntities();
                    int userId = (int)Session["userId"];

                    IEnumerable<User> users = from usrs in db.Users
                                              where usrs.id == userId
                                              select usrs;

                    User user;

                    try
                    {

                        user = users.FirstOrDefault();
                    }
                    catch (NullReferenceException ex)
                    {
                        ViewBag.Error = "Occurred an error whlie accessing your profile...Please try again or contact the administrator.";
                        Utils.writeLog("[Controller: " + RouteData.Values["controller"].ToString() + "]\n[Action method: " + RouteData.Values["action"].ToString() + "]\n[Error: " + ViewBag.Error + "]\n[Exception message:\n\n" + ex.InnerException.Message + "]");
                        return View("RegisterReponse");
                    }

PRAXISNETWORK/PRAXISNETWORK/Controllers/StudentController.cs
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PRAXISNETWORK.Controllers
{
    /// <summary>
    /// Handles all requests of a student when authenticated
    /// </summary>
    public class StudentController : Controller
    {
        /// <summary>
        /// Shows html page with the student´s management board
        /// </summary>
        /// <returns>Html page student´s management board</returns>
        public ActionResult Index()
        {
            if (Session["userId"] != null && (int)Session["userType"] == 2)
            {

                ViewBag.Title = "Student board";

                return View();
            }
            else
            {
                return RedirectToAction("Index", "Login");
            }
        }

        /// <summary>
        /// Shows all the proposal´s offer applications made by the student
        /// </summary>
        /// <param name="page">Pagination´s page number</param>
        /// <param name="pageSize">pagination´s number of proposal´s offer applications per page</param>
        /// <returns>Html page with all proposal´s offer applications</returns>
        public ActionResult StudentApplications(int page = 1, int pageSize = 5)
        {
            if (Session["userId"] != null && (int)Session["userType"] == 2)
            {

                int userId = (int)Session["userID"];
                

                ViewBag.Title = "Your applications";
                Models.StudentApplications studentApps = new Models.StudentApplications()
                {

                    userId = userId,
                    page = page,
                    pageSize = pageSize
                };

                return View(studentApps);
            }
            else
            {
                return RedirectToAction("Index", "Login");
            }
        }

    }
}

PRAXISNETWORK/PRAXISNETWORK/Views/Register/AllProvidersPartialView.cshtml
@model PRAXISNETWORK.Models.AllProviders

@{
    int dropLockedNumber = 0;
    int dropEnabledNumber = 0;
}

<table class="table table-bordered table-hover">
    @if (Model.allProviders().Count() == 0)
    {
        <tr>
            <td><b>There are no providers registered...</b></td>
        </tr>
    }
    else
    {
        <thead>
        <th><b>NAME</b></th>
        <th><b>EMAIL</b></th>
        <th><b>LAST LOGIN</b></th>
        <th><b>LOCKED</b></th>
        <th><b>ENABLED</b></th>
        <th><b>ACTION</b></th>
        <th><b>ACTION</b></th>
        </thead>
        foreach (var app in Model.allProviders())
        {
            <tr>
                <td>@Html.ActionLink(@app.username, "ShowProvider", "Register", new { @id = @app.id }, null)</td>
                <td>@Html.ActionLink(@app.email, "ShowProvider", "Register", new { @id = @app.id }, null)</td>
                <td>@Html.ActionLink(@app.lastLogin, "ShowProvider", "Register", new { @id = @app.id }, null)</td>
                <td>@Html.DropDownList("dropLocked_" + @dropLockedNumber, app.locked, new { @onchange = "ChangeLockedStatus(" + (@dropLockedNumber++) + ")" })</td>
                <td>@Html.DropDownList("dropEnabled_" + @dropEnabledNumber, app.enabled, new { @onchange = "ChangeEnabledStatus(" + (@dropEnabledNumber++) + ")" })</td>
                <td>@Html.ActionLink("Show proposals...", "ProvidersProposals", "Administrator", new { @providerId = @app.id }, new { @class = "btn btn-default" })</td>
                <td><button type="button" class="btn btn-default" data-toggle="modal" data-target="#deleteProvider" id="deleteConfProvider_@app.id" onclick="updateProviderId(@app.id)">Delete provider...</button></td>
            </tr>
        }
    }
</table>

PRAXISNETWORK/PRAXISNETWORK/Views/Register/AllStudents.cshtml
@model PRAXISNETWORK.Models.AllStudents
@using PagedList.Mvc

@{
    Layout = "~/Views/Shared/_Master.cshtml";
    int dropLockedNumber = 0;
    int dropEnabledNumber = 0;
}

@section title{

    @ViewBag.Title
}

@section header{
    <script src="~/Scripts/Register/AllStudents.js"></script>
}

<div class="container">

    <div class="row">
        <div class="col-md-10 col-md-offset-1">
            <h2>@ViewBag.Title</h2>
            <hr />
        </div>
    </div>
    <br />
    <div class="row">
        <div class="col-md-10 col-md-offset-1">
            <div id="students">
                <table class="table table-bordered table-hover">
                    @if (Model.allProviders().Count() == 0)
                    {
                        <tr>
                            <td><b>There are no students registered...</b></td>
                        </tr>
                    }
                    else
                    {
                        <thead>
                        <th><b>NAME</b></th>
                        <th><b>EMAIL</b></th>
                        <th><b>LAST LOGIN</b></th>
                        <th><b>LOCKED</b></th>
                        <th><b>ENABLED</b></th>
                        <th><b>ACTION</b></th>
                        <th><b>ACTION</b></th>
                        </thead>
                        foreach (var app in Model.allProviders())
                        {
                            <tr>
                                <td>@Html.ActionLink(@app.username, "ShowStudent", "Register", new { @id = @app.id }, null)</td>
                                <td>@Html.ActionLink(@app.email, "ShowStudent", "Register", new { @id = @app.id }, null)</td>
                                <td>@Html.ActionLink(@app.lastLogin, "ShowStudent", "Register", new { @id = @app.id }, null)</td>
                                <td>@Html.DropDownList("dropLocked_" + @dropLockedNumber, app.locked, new { @onchange = "ChangeLockedStatus(" + (@dropLockedNumber++) + ")" })</td>
                                <td>@Html.DropDownList("dropEnabled_" + @dropEnabledNumber, app.enabled, new { @onchange = "ChangeEnabledStatus(" + (@dropEnabledNumber++) + ")" })</td>
                                <td>@Html.ActionLink("Show proposals applications...", "StudentProposals", "Administrator", new { @studentId = @app.id }, new { @class = "btn btn-default" })</td>
                                <td><button type="button" class="btn btn-default" data-toggle="modal" data-target="#deleteStudent" id="deleteConfStudent_@app.id" onclick="updateStudentId(@app.id)">Delete student...</button></td>
                            </tr>
                        }
                    }
                </table>
            </div>
            <div class="center-block">
                @Html.PagedListPager(Model.allProviders(), page => Url.Action("AllProviders", "Register", new { page, pageSize = Model.pageSize }))
                <b>Showing @Model.allProviders().FirstItemOnPage to @Model.allProviders().LastItemOnPage of @Model.allProviders().TotalItemCount providers</b>
            </div>
            <hr />
        </div>
    </div>
</div>

<div class="modal fade" role="dialog" id="deleteStudent">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Student deletion...</h4>
            </div>
            <div class="modal-body">
                <p>Do you want to confirm student deletion?</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                <button class="btn btn-danger" onclick="deleteStudentConfirmation()">CONFIRM</button>
            </div>
        </div>
    </div>
</div>

PRAXISNETWORK/PRAXISNETWORK/Views/Register/AllStudentsPartialView.cshtml
@model PRAXISNETWORK.Models.AllStudents

@{
    int dropLockedNumber = 0;
    int dropEnabledNumber = 0;
}

<table class="table table-bordered table-hover">
    @if (Model.allProviders().Count() == 0)
    {
        <tr>
            <td><b>There are no students registered...</b></td>
        </tr>
    }
    else
    {
        <thead>
        <th><b>NAME</b></th>
        <th><b>EMAIL</b></th>
        <th><b>LAST LOGIN</b></th>
        <th><b>LOCKED</b></th>
        <th><b>ENABLED</b></th>
        <th><b>ACTION</b></th>
        <th><b>ACTION</b></th>
        </thead>
        foreach (var app in Model.allProviders())
        {
            <tr>
                <td>@Html.ActionLink(@app.username, "ShowStudent", "Register", new { @id = @app.id }, null)</td>
                <td>@Html.ActionLink(@app.email, "ShowStudent", "Register", new { @id = @app.id }, null)</td>
                <td>@Html.ActionLink(@app.lastLogin, "ShowStudent", "Register", new { @id = @app.id }, null)</td>
                <td>@Html.DropDownList("dropLocked_" + @dropLockedNumber, app.locked, new { @onchange = "ChangeLockedStatus(" + (@dropLockedNumber++) + ")" })</td>
                <td>@Html.DropDownList("dropEnabled_" + @dropEnabledNumber, app.enabled, new { @onchange = "ChangeEnabledStatus(" + (@dropEnabledNumber++) + ")" })</td>
                <td>@Html.ActionLink("Show proposals applications...", "StudentProposals", "Administrator", new { @studentId = @app.id }, new { @class = "btn btn-default" })</td>
                <td><button type="button" class="btn btn-default" data-toggle="modal" data-target="#deleteStudent" id="deleteConfStudent_@app.id" onclick="updateStudentId(@app.id)">Delete student...</button></td>
            </tr>
        }
    }
</table>

PRAXISNETWORK/PRAXISNETWORK/Views/Register/Provider.cshtml
@model PRAXISNETWORK.ModelViews.Register.Provider

@{
    ViewBag.Title = "Provider";
    Layout = "~/Views/Shared/_Master.cshtml";
}

@section title{

    @ViewBag.Title
}

@section header{

    <script src="~/Scripts/Register/ProviderView.js"></script>
}

@using (Html.BeginForm("SaveProvider", "Register", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="container-fluid">

        <div class="row">
            <div class="col-md-10 col-md-offset-1">
                <h1>Register as provider</h1>
                <hr />
            </div>
        </div>
        <br />
        <div class="row">
            <div class="col-md-5 col-md-offset-1">
                <h2>User information</h2>
                <br />
                <div class="form-group">
                    @Html.LabelFor(model => model.username)
                    @Html.EditorFor(model => model.username)
                    @Html.ValidationMessageFor(model => model.username)
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.firstName)
                    @Html.EditorFor(model => model.firstName)
                    @Html.ValidationMessageFor(model => model.firstName)
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.lastName)
                    @Html.EditorFor(model => model.lastName)
                    @Html.ValidationMessageFor(model => model.lastName)
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.email)
                    @Html.EditorFor(model => model.email)
                    @Html.ValidationMessageFor(model => model.email)
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.password)
                    @Html.PasswordFor(model => model.password)
                    @Html.ValidationMessageFor(model => model.password)
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.passwordConfirmation)
                    @Html.PasswordFor(model => model.passwordConfirmation)
                    @Html.ValidationMessageFor(model => model.passwordConfirmation)
                </div>
            </div>
            <div class="col-md-5">
                <h2>Institution information</h2>
                <br />
                @Html.LabelFor(model => model.isOldInstitution)
                @Html.DropDownListFor(model => model.isOldInstitution, Model.ListOfInstitutionsInfo())
                <div id="institution">
                    @Html.Partial("ProviderNewInstitutionPartialView")
                </div>
            </div>
        </div>
        <br />
        <div class="row">
            <div class="col-md-10 col-md-offset-1">
                <hr />
                <input type="submit" value="REGISTER" class="btn btn-warning" />
            </div>
        </div>
    </div>
}

PRAXISNETWORK/PRAXISNETWORK/Views/Register/ProviderEdition.cshtml
@model PRAXISNETWORK.ModelViews.Register.Provider

@{
    Layout = "~/Views/Shared/_Master.cshtml";
}

@section title{

    @ViewBag.Title
}

@section header{

    <script src="~/Scripts/Register/ProviderEditionView.js"></script>
}

@using (Html.BeginForm("UpdateProvider", "Register", FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="container-fluid">

        <div class="row">
            <div class="col-md-10 col-md-offset-1">
                <h1>@ViewBag.Title</h1>
                <hr />
            </div>
        </div>
        <br />
        <div class="row">
            <div class="col-md-5 col-md-offset-1">
                <h2>User information</h2>
                <br />
                <div class="form-group">
                    @Html.LabelFor(model => model.firstName)
                    @Html.EditorFor(model => model.firstName)
                    @Html.ValidationMessageFor(model => model.firstName)
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.lastName)
                    @Html.EditorFor(model => model.lastName)
                    @Html.ValidationMessageFor(model => model.lastName)
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.password)
                    @Html.PasswordFor(model => model.password)
                    @Html.ValidationMessageFor(model => model.password)
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.passwordConfirmation)
                    @Html.PasswordFor(model => model.passwordConfirmation)
                    @Html.ValidationMessageFor(model => model.passwordConfirmation)
                </div>
            </div>
            <div class="col-md-4">
                <h2>Localization information</h2><br />
                @Html.LabelFor(model => model.isOldInstitution)<br />
                @Html.DropDownListFor(model => model.isOldInstitution, Model.ListOfInstitutionsInfo())
                <div id="institution">
                    @if (Model.isOldInstitution == "1")
                    {
                        @Html.Partial("ProviderEditionNewInstitutionPartialView")
                    }
                    else if (Model.isOldInstitution == "2")
                    {
                        @Html.Partial("ProviderEditionOldInstitutionPartialView")
                    }

                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-10 col-md-offset-1">
                <hr />
                <input type="submit" value="UPDATE" class="btn btn-warning" />
                <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#deleteProfile">DELETE MY PROFILE</button>
            </div>
        </div>
    </div>
}

<div class="modal fade" id="deleteProfile" tabindex="-1" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title"><b>Profile deletion...</b></h4>
            </div>
            <div class="modal-body">
                <p>
                    Deleting your profile will erase all your related information about previous and current proposals among others things.
                    <br />
                    <br />
                    Do you really want to delete your profile?
                </p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                <a class="btn btn-danger" href="/Register/DeleteProfile">DELETE PROFILE</a>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

PRAXISNETWORK/PRAXISNETWORK/Views/Register/ProviderEditionNewInstitutionPartialView.cshtml
@model PRAXISNETWORK.ModelViews.Register.Provider

<br />
<div class="form-group">
    @Html.LabelFor(model => model.country)
    @Html.DropDownListFor(model => model.country, Model.ListsOfCountriesAndCitiesSelected()["countries"])
</div>
<div class="form-group">
    @Html.LabelFor(model => model.city)
    @Html.DropDownListFor(model => model.city, Model.ListsOfCountriesAndCitiesSelected()["cities"])
</div>

PRAXISNETWORK/PRAXISNETWORK/Views/Register/ProviderEditionOldInstitutionPartialView.cshtml
@model PRAXISNETWORK.ModelViews.Register.Provider

<br />
<div class="form-group">
    @Html.LabelFor(model => model.selectedInstitution)
    <div>
        @Html.DropDownListFor(model => model.selectedInstitution, Model.ListOfInstitutionsSelected())
    </div>
</div>