PRAXISNETWORK/PRAXISNETWORK/Controllers/AdministratorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PRAXISNETWORK.Controllers
{
    /// <summary>
    /// Handles administrator´s requests
    /// </summary>
    public class AdministratorController : Controller
    {
        /// <summary>
        /// Shows administrator´s management borad
        /// </summary>
        /// <returns></returns>
        public ActionResult Index()
        {
            if (Session["userId"] != null && (int)Session["userType"] == 3)
            {

                ViewBag.Title = "Administrator board";

                return View();
            }
            else
            {
                return RedirectToAction("AdminAuthentication", "Login");
            }
        }

        public ActionResult ProviderProposals(int providerId, int page = 1, int pageSize = 5)
        {
            if (Session["userId"] != null && (int)Session["userType"] == 3)
            {

                ViewBag.Title = "Provider proposals";
                Models.ProviderProposals providerProps = new Models.ProviderProposals()
                {

                    userId = providerId,
                    page = page,
                    pageSize = pageSize
                };

                return View(providerProps);
            }
            else
            {
                return RedirectToAction("AdminLogin", "Login");
            }
        }

        public ActionResult StudentProposals(int studentId, int page = 1, int pageSize = 5)
        {
            if (Session["userId"] != null && (int)Session["userType"] == 3)
            {

                ViewBag.Title = "Student proposals applications";
                Models.StudentApplications studentApps = new Models.StudentApplications()
                {

                    userId = studentId,
                    page = page,
                    pageSize = pageSize
                };

                return View(studentApps);
            }
            else
            {
                return RedirectToAction("AdminLogin", "Login");
            }
        }
    }
}

PRAXISNETWORK/PRAXISNETWORK/Controllers/NewsController.cs
using PRAXISNETWORK.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Xml.Linq;

namespace PRAXISNETWORK.Controllers
{
    /// <summary>
    /// Handles all information about news feeds and newsletters requests
    /// </summary>
    public class NewsController : Controller
    {
        /// <summary>
        /// Shows a html page to subscribe the newsletter mechanism
        /// </summary>
        /// <returns>Html page fill with the subscriber´s email address</returns>
        public ActionResult NewSubscriber()
        {
            ViewBag.Title = "New subscriber";
            ModelViews.News.NewSubscriber subscriber = new ModelViews.News.NewSubscriber();
            return View(subscriber);
        }

        /// <summary>
        /// Saves new newsletter´s subscriber
        /// </summary>
        /// <param name="newSubscriber">Model object with the current ´subscriber´s data</param>
        /// <returns>Html page process' result</returns>
        public ActionResult SaveSubscriber(ModelViews.News.NewSubscriber newSubscriber)
        {
            if (ModelState.IsValid)
            {
                ViewBag.Title = "Subscription result";
                Models.PraxisDBEntities db = new Models.PraxisDBEntities();

                Models.Subscriber subscriberRecord = new Models.Subscriber()
                {
                    name = (newSubscriber.name != null ? newSubscriber.name : null),
                    email = newSubscriber.email,
                    subscriptionDate = DateTime.Now
                };

                db.Subscribers.Add(subscriberRecord);

                try
                {
                    db.SaveChanges();
                }
                catch (Exception ex)
                {
                    ViewBag.Error = "Occurred an error while saving your subscription...Please try again or contact the administrator.";
                    Utils.writeLog("[Controller: " + RouteData.Values["controller"].ToString() + "]\n[Action method: " + RouteData.Values["action"].ToString() + "]\n[Error: " + ViewBag.Error + "]\n[Exception message:\n\n" + ex.InnerException.Message + "]");
                    return View("NewsResponse");
                }

                ViewBag.Success = "YOUR SUBSCRIPTION WAS SUCCESSFUL!!!";
                return View("NewsResponse");
            }
            else
            {
                ViewBag.Title = "New subscriber";
                return View("NewSubscriber", newSubscriber);
            }
        }

        /// <summary>
        /// Handles requet to send Rss Feed to Rss Feed´s clients with current proposal´s offers
        /// </summary>
        /// <returns>Standard Rss Feed´s XML Document</returns>
        public XDocument RssFeed()
        {
            PraxisDBEntities db = new PraxisDBEntities();

            IEnumerable<Proposal> allProposals = from props in db.Proposals
                                                 where props.validTo.CompareTo(DateTime.Now) >= 0
                                                 select props;

            XElement channel = new XElement("channel",
                                    new XElement("title", "Proposals´s Rss Feeds"),
                                    new XElement("link", "http://localhost:63178/Proposals"),
                                    new XElement("Description", "This Rss Feed has information about proposals that are up to the date valid for application"));

            if (allProposals.ToList() != null && allProposals.ToList().Count() > 0)
            {
                foreach (Proposal proposal in db.Proposals)
                {
                    int end = (int)(proposal.description.Length * 0.3);
                    String title = proposal.title;
                    String description = proposal.description.Substring(0, end) + "\n(Click the link below to see offer´s information...)";
                    String OfferLink = "http://localhost:63178/Proposals/ProposalShow/" + proposal.id;

                    XElement item = new XElement("item",
                                        new XElement("title", title),
                                        new XElement("description", description),
                                        new XElement("link", OfferLink));

                    channel.Add(item);
                }

                XElement rssFeed = new XElement("rss",
                                    new XAttribute("version", "2.0"),
                                    channel);

                XDocument doc = new XDocument(new XDeclaration("1.0", "UTF-8", "yes"), rssFeed);



                return doc;
            }
            else return null;
        }
    }
}

PRAXISNETWORK/PRAXISNETWORK/Controllers/ProviderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PRAXISNETWORK.Controllers
{
    /// <summary>
    /// Handles all requests of an authenticated provider
    /// </summary>
    public class ProviderController : Controller
    {
        /// <summary>
        /// Shows main board of management for the provider
        /// </summary>
        /// <returns>Html page with management board</returns>
        public ActionResult Index()
        {
            if (Session["userId"] != null && (int)Session["userType"] == 1)
            {

                ViewBag.Title = "Provider board";

                return View();
            }
            else
            {
                return RedirectToAction("Index", "Login");
            }
        }

        /// <summary>
        /// Shows all proposals´ offers made by the provider
        /// </summary>
        /// <param name="page">Pagination´s page number</param>
        /// <param name="pageSize">Pagination´s number of proposals to display by page</param>
        /// <returns>Html page with all proposals offers</returns>
        public ActionResult ProviderProposals(int page = 1, int pageSize = 5)
        {
            if (Session["userId"] != null && (int)Session["userType"] == 1)
            {

                int userId = (int)Session["userID"];


                ViewBag.Title = "Your proposals";
                Models.ProviderProposals providerProps = new Models.ProviderProposals()
                {

                    userId = userId,
                    page = page,
                    pageSize = pageSize
                };

                return View(providerProps);
            }
            else
            {
                return RedirectToAction("Index", "Login");
            }
        }

    }
}

PRAXISNETWORK/PRAXISNETWORK/Controllers/StudentController.cs
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PRAXISNETWORK.Controllers
{
    /// <summary>
    /// Handles all requests of a student when authenticated
    /// </summary>
    public class StudentController : Controller
    {
        /// <summary>
        /// Shows html page with the student´s management board
        /// </summary>
        /// <returns>Html page student´s management board</returns>
        public ActionResult Index()
        {
            if (Session["userId"] != null && (int)Session["userType"] == 2)
            {

                ViewBag.Title = "Student board";

                return View();
            }
            else
            {
                return RedirectToAction("Index", "Login");
            }
        }

        /// <summary>
        /// Shows all the proposal´s offer applications made by the student
        /// </summary>
        /// <param name="page">Pagination´s page number</param>
        /// <param name="pageSize">pagination´s number of proposal´s offer applications per page</param>
        /// <returns>Html page with all proposal´s offer applications</returns>
        public ActionResult StudentApplications(int page = 1, int pageSize = 5)
        {
            if (Session["userId"] != null && (int)Session["userType"] == 2)
            {

                int userId = (int)Session["userID"];
                

                ViewBag.Title = "Your applications";
                Models.StudentApplications studentApps = new Models.StudentApplications()
                {

                    userId = userId,
                    page = page,
                    pageSize = pageSize
                };

                return View(studentApps);
            }
            else
            {
                return RedirectToAction("Index", "Login");
            }
        }

    }
}

PRAXISNETWORK/PRAXISNETWORK/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <title>@ViewBag.Title - My ASP.NET MVC Application</title>
        <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
        <meta name="viewport" content="width=device-width" />
        @Styles.Render("~/Content/css")
        @Scripts.Render("~/bundles/modernizr")
    </head>
    <body>
        <header>
            <div class="content-wrapper">
                <div class="float-left">
                    <p class="site-title">@Html.ActionLink("your logo here", "Index", "Home")</p>
                </div>
                <div class="float-right">
                    <section id="login">
                        @Html.Partial("_LoginPartial")
                    </section>
                    <nav>
                        <ul id="menu">
                            <li>@Html.ActionLink("Home", "Index", "Home")</li>
                            <li>@Html.ActionLink("About", "About", "Home")</li>
                            <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                        </ul>
                    </nav>
                </div>
            </div>
        </header>
        <div id="body">
            @RenderSection("featured", required: false)
            <section class="content-wrapper main-content clear-fix">
                @RenderBody()
            </section>
        </div>
        <footer>
            <div class="content-wrapper">
                <div class="float-left">
                    <p>&copy; @DateTime.Now.Year - My ASP.NET MVC Application</p>
                </div>
            </div>
        </footer>

        @Scripts.Render("~/bundles/jquery")
        @RenderSection("scripts", required: false)
    </body>
</html>

PRAXISNETWORK/PRAXISNETWORK/Views/Shared/_Master.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@RenderSection("title")</title>
    <script src="~/Scripts/jquery-1.9.1.js"></script>
    @*<script src="~/Scripts/jquery-1.8.3.js"></script>*@
    <script src="~/Scripts/jquery-ui-1.8.24.js"></script>
    <script src="~/Scripts/jquery.form.js"></script>
    <script src="~/Scripts/jquery.validate.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>
    @*<script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>*@
    <link href="~/Scripts/Bootstrap/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Scripts/Bootstrap/css/bootstrap-theme.min.css" rel="stylesheet" type="text/css" media="screen" />
    <script src="~/Scripts/Bootstrap/js/bootstrap.min.js"></script>
    <link href="~/Scripts/Bootstrap/css/bootstrap.icon-large.min.css" rel="stylesheet" />
    <script src="~/Scripts/FancyBox/source/jquery.fancybox.pack.js"></script>
    <link href="~/Scripts/FancyBox/source/jquery.fancybox.css" rel="stylesheet" />
    <script src="~/Scripts/FancyBox/lib/jquery.mousewheel-3.0.6.pack.js"></script>

    @if (IsSectionDefined("header"))
    {
        @RenderSection("header")
    }
</head>
<body style="padding-top: 70px; padding-bottom:70px">
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container" style="padding:10px; vertical-align: central">
            <div class="col-md-7">
                @Html.ActionLink("LOGIN | ", "Index", "Login", null, new { @style = "color: white" })
                @Html.ActionLink("REGISTER | ", "Index", "Register", null, new { @style = "color: white" })
                @Html.ActionLink("PROPOSALS |", "Index", "Proposals", null, new { @style = "color: white" })
                @Html.ActionLink("SUBSCRIBE ", "NewSubscriber", "News", null, new { @style = "color: white" })
                @using (Html.BeginForm("ProposalsSearchMaster", "Proposals", FormMethod.Post, new { @style = "display: inline" }))
                {
                    @Html.AntiForgeryToken()

                    <input type="text" name="searchField" id="searchField" placeholder="Search projects/internships..." style="width:30%" />

                }
            </div>
            <div class="col-md-5 col-md-offset-2">

            </div>
        </div>
    </nav>
    <div>
        @RenderBody();
    </div>
    <nav class="navbar navbar-inverse navbar-fixed-bottom">
        <div class="container">
            <div class="container" style="padding:10px; color: white; vertical-align: central">
                <div class="row">
                    <div class="col-sm-8">
                        @if (Session["userID"] != null)
                        {
                            if (((int)Session["userType"]) == 2)
                            {
                                @Html.ActionLink("STUDENT BOARD", "Index", "Student", null, new { @style = "color: white" })
                            }

                            if (((int)Session["userType"]) == 1)
                            {
                                @Html.ActionLink("PROVIDER BOARD", "Index", "Provider", null, new { @style = "color: white" })
                            }

                            if (((int)Session["userType"]) == 3)
                            {
                                @Html.ActionLink("ADMINISTRATOR BOARD", "Index", "Administrator", null, new { @style = "color: white" })
                            }
                        }
                        else
                        {
                            <i>@Html.ActionLink("Administration", "AdminLogin", "login", null, new { @style = "color: white" })</i>
                        }
                    </div>
                    <div class="col-sm-4">
                        @if (this.Session["userID"] != null)
                        {
                            <a href="/Login/Logout" class="btn btn-danger">LOGOUT</a>  <b>@((String)this.Session["userName"])</b>
                        }
                    </div>
                </div>
            </div>
        </div>
    </nav>
</body>
</html>

PRAXISNETWORK/PRAXISNETWORK/Views/Shared/_html5shiv.cshtml
   <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="~/scripts/html5shiv.js"></script>
    <![endif]-->