PRAXISNETWORK/PRAXISNETWORK/Controllers/ProposalsController.cs
using PRAXISNETWORK.Models;
using PRAXISNETWORK.ModelViews.Proposals;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System.Transactions;
using System.Web;
using System.Web.Mvc;

namespace PRAXISNETWORK.Controllers
{
    /// <summary>
    /// Handles requests concerned about proposal´s offers
    /// </summary>
    public class ProposalsController : Controller
    {
        /// <summary>
        /// Shows main html page with all proposals´ offers available
        /// </summary>
        /// <param name="page">Pagination´s page number</param>
        /// <param name="pageSize">Pagination´s number of proposals displayed by page</param>
        /// <returns>Html page with all proposals´ offers</returns>
        public ActionResult Index(int page = 1, int pageSize = 5)
        {
            ProposalSearch pSearch = new ProposalSearch();
            pSearch.page = page;
            pSearch.pageSize = pageSize;
            ViewBag.Title = "Find project/Internship";

            return View(pSearch);
        }

        /// <summary>
        /// Shows a specific proposal´s offer information
        /// </summary>
        /// <param name="Id">Proposal´s offer identification number</param>
        /// <returns>Html page with proposal´s offer information</returns>
        public ActionResult ProposalShow(int Id)
        {
            PraxisDBEntities db = new PraxisDBEntities();

            ProposalShow currentProposal = (from proposals in db.Proposals
                                            join cities in db.Cities on proposals.cityId equals cities.id
                                            join countries in db.Countries on cities.countryId equals countries.id
                                            join institutions in db.Institutions on proposals.institutionId equals institutions.id
                                            join hosts in db.Institutions on proposals.hostId equals hosts.id
                                            where proposals.id == Id && proposals.visible == true && proposals.deleted == false && proposals.applyOnPraxis == true
                                            select new ProposalShow
                                            {
                                                id = proposals.id,
                                                providerId = proposals.providerId,
                                                title = proposals.title,
                                                description = proposals.description,
                                                city = cities.name,
                                                country = countries.name,
                                                supervisorFirtLastName = proposals.supervisorFirstName + " " + proposals.supervisorLastName,
                                                supervisorEmail = proposals.supervisorEmail,
                                                startDate = proposals.startDate,
                                                endDate = proposals.endDate,
                                                validationDate = proposals.validTo,
                                                payment = proposals.payment,
                                                vacancies = proposals.vacancies,
                                                benefits = proposals.benefits,
                                                globalsSkills = proposals.globalSkills,
                                                jobRelatedSkills = proposals.jobRelatedSkills,
                                                contact = proposals.contact,
                                                Institution = institutions.name,
                                                host = hosts.name
                                            }).FirstOrDefault();

            IEnumerable<Language> allLanguages = from languages in db.Languages
                                                 join propLanguages in db.ProposalLanguages on languages.id equals propLanguages.languageId
                                                 where propLanguages.proposalId == Id
                                                 select languages;

            IEnumerable<Skill> allPromotedSkills = from skills in db.Skills
                                                   join promoteSkills in db.PromotedSkills on skills.id equals promoteSkills.skillId
                                                   where promoteSkills.proposalId == Id
                                                   select skills;

            IEnumerable<Target> allTargets = from targets in db.Targets
                                             join propTargets in db.ProposalsTargets on targets.id equals propTargets.targetId
                                             where propTargets.proposalId == Id
                                             select targets;

            IEnumerable<StudyArea> allAreas = from areas in db.StudyAreas
                                              join propAreas in db.ProposalStudyAreas on areas.id equals propAreas.studyAreaId
                                              where propAreas.proposalId == Id
                                              select areas;

            IEnumerable<StudyDegree> allDegrees = from degrees in db.StudyDegrees
                                                  join propDegrees in db.ProposalStudyDegrees on degrees.id equals propDegrees.studyDegreeId
                                                  where propDegrees.proposalId == Id
                                                  select degrees;

            // Languages
            if (allLanguages.ToList() != null && allLanguages.ToList().Count() > 0)
                foreach (Language language in allLanguages)
                    currentProposal.languages += language.name + "; ";

            // Skills to promote
            if (allPromotedSkills.ToList() != null && allPromotedSkills.ToList().Count() > 0)
                foreach (Skill skill in allPromotedSkills)
                    currentProposal.promotedSkills += skill.name + "; ";

            // Targets
            if (allTargets.ToList() != null && allTargets.ToList().Count() > 0)
                foreach (Target target in allTargets)
                    currentProposal.targets += target.name + "; ";

            // Study areas
            if (allAreas.ToList() != null && allAreas.ToList().Count() > 0)
                foreach (StudyArea area in allAreas)
                    currentProposal.studyAreas += area.name + "; ";

            // Study degrees
            if (allDegrees.ToList() != null && allDegrees.ToList().Count() > 0)
                foreach (StudyDegree degree in allDegrees)
                    currentProposal.studyDegrees += degree.name + "; ";

            // Format dates
            currentProposal.startDateText = currentProposal.startDate.ToString("yyyy-MM-dd");
            currentProposal.endDateText = currentProposal.endDate.ToString("yyyy-MM-dd");
            currentProposal.validationDateText = currentProposal.validationDate.ToString("yyyy-MM-dd");

            // Null values
            if (String.IsNullOrEmpty(currentProposal.globalsSkills))
                currentProposal.globalsSkills = "None";

            if (String.IsNullOrEmpty(currentProposal.jobRelatedSkills))
                currentProposal.jobRelatedSkills = "None";

            if (String.IsNullOrEmpty(currentProposal.payment))
                currentProposal.payment = "None";

            if (String.IsNullOrEmpty(currentProposal.vacancies))
                currentProposal.vacancies = "None";


            if (Session["userId"] != null)
            {
                int userId = (int)Session["userId"];

                // Check if the provider user has applications for this proposal
                if ((int)Session["userType"] == 1)
                {
                    IEnumerable<Models.Proposal> allProposals = from props in db.Proposals
                                                                join apps in db.Applications on props.id equals apps.proposalId
                                                                where props.providerId == userId
                                                                select props;

                    if (allProposals != null && allProposals.Count() > 0)
                        currentProposal.hasApplications = true;
                    else currentProposal.hasApplications = false;
                }

                // Check if the user as a student already has applied to the proposal
                if ((int)Session["userType"] == 2)
                {

                    IEnumerable<Application> applications = from apps in db.Applications
                                                            where apps.userId == userId && apps.proposalId == currentProposal.id
                                                            select apps;

                    try
                    {
                        int propId = -1;
                        propId = applications.FirstOrDefault().proposalId;

                        if (propId != -1)
                            currentProposal.userAlreadyApplied = true;
                    }
                    catch (NullReferenceException ex)
                    {
                        currentProposal.userAlreadyApplied = false;
                    }
                }
                else
                {
                    currentProposal.userAlreadyApplied = false;
                }
            }


            ViewBag.Title = currentProposal.title;

            return View("ProposalShow", currentProposal);
        }

        /// <summary>
        /// Shows html page to add a new proposal´s offer by a provider
        /// </summary>
        /// <returns>Html page for the new proposal´s offer</returns>

PRAXISNETWORK/PRAXISNETWORK/Views/Proposals/Index.cshtml
@model PRAXISNETWORK.ModelViews.Proposals.ProposalSearch
@using PagedList.Mvc

@{
    Layout = "~/Views/Shared/_Master.cshtml";
}

@section title{
    @ViewBag.Title
}

<div class="container">

    <div class="row">
        <div class="col-md-10 col-md-offset-1">
            <h2>Find international projects and internships</h2><br />
            <hr />
        </div>
    </div>
    <br />
    <div class="row">

        <div class="col-md-4 col-md-offset-1">
            @using (Html.BeginForm("ProposalsFilter", "Proposals", FormMethod.Post))
            {
                @Html.AntiForgeryToken()

                <div class="form-group">
                    @Html.LabelFor(model => model.targets)<br />
                    @Html.ListBoxFor(model => model.targets, new MultiSelectList(Model.AllTargets(), "Value", "Text"))
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.studyDegrees)<br />
                    @Html.ListBoxFor(model => model.studyDegrees, new MultiSelectList(Model.AllStudyDegrees(), "Value", "Text"))
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.durations)<br />
                    @Html.ListBoxFor(model => model.durations, new MultiSelectList(Model.AllDurations(), "Value", "Text"))
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.country)<br />
                    @Html.DropDownListFor(model => model.country, Model.AllCountries(), new { @style = "width: 50%" })
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.studyArea)<br />
                    @Html.DropDownListFor(model => model.studyArea, Model.AllStudyAreas())
                </div>
                <div>
                    <input type="submit" value="FILTER" class="btn btn-warning" />
                </div>
            }
        </div>

        <div class="col-md-7">
            @using (Html.BeginForm("ProposalsSearch", "Proposals", FormMethod.Post))
            {
                @Html.AntiForgeryToken()

                <div class="form-group">
                    @Html.LabelFor(model => model.searchField)<br />
                    @Html.EditorFor(model => model.searchField, new { @style = "width: 100%" })
                    <input type="submit" value="SEARCH" class="btn btn-warning" />
                </div>
            }
            <div id="projects">
                @foreach (var proposal in Model.AllProposals())
                {
                    <div>
                        <h3>@proposal.title</h3>
                        <br />
                        @Html.Label("City:") @proposal.city<br />
                        @Html.Label("Study area:") @proposal.studyAreas<br />
                        @Html.Label("Study degree:") @proposal.studyDegrees<br />
                        @Html.Label("Institution:") @proposal.institution<br />
                        @Html.ActionLink("READ COMPLETE OFFER >>", "ProposalShow", "Proposals", new { @Id = proposal.id }, null)
                    </div>
                    <hr />
                }
            </div>
            <div class="center-block">
                @Html.PagedListPager(Model.AllProposals(), page => Url.Action("Index", "Proposals", new { page, pageSize = Model.AllProposals().PageSize }))
                <b>Showing @Model.AllProposals().FirstItemOnPage to @Model.AllProposals().LastItemOnPage of @Model.AllProposals().TotalItemCount projects/internships</b>
            </div>
        </div>
    </div>
</div>

PRAXISNETWORK/PRAXISNETWORK/Views/Proposals/NewProposal.cshtml
@model PRAXISNETWORK.ModelViews.Proposals.Proposal

@{
    Layout = "~/Views/Shared/_Master.cshtml";
}

@section title{
    @ViewBag.Title
}

@section header{
    <script src="~/Scripts/Proposals/NewProposalView.js"></script>
}

@using (Html.BeginForm("SaveProposal", "Proposals", FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="container">

        <div class="row">
            <div class="col-md-10 col-md-offset-1">
                <h1>Add new proposal</h1>
                <hr />
            </div>
        </div>
        <br />
        <div class="row">
            <div class="col-md-5 col-md-offset-1">
                <h2>Proposal information</h2>
                <br />
                <div class="form-group">
                    @Html.LabelFor(model => model.title)
                    @Html.EditorFor(model => model.title)
                    @Html.ValidationMessageFor(model => model.title)
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.description)<br />
                    @Html.EditorFor(model => model.description)
                    @Html.ValidationMessageFor(model => model.description)
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.targets)<br />
                    @Html.ListBoxFor(model => model.targets, new MultiSelectList(Model.AllTargets(), "Value", "Text"))
                    @Html.ValidationMessageFor(model => model.targets)
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.startDate)
                    @Html.EditorFor(model => model.startDate)
                    @Html.ValidationMessageFor(model => model.startDate)
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.endDate)
                    @Html.EditorFor(model => model.endDate)
                    @Html.ValidationMessageFor(model => model.endDate)
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.validTo)
                    @Html.EditorFor(model => model.validTo)
                    @Html.ValidationMessageFor(model => model.validTo)
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.payment)
                    @Html.EditorFor(model => model.payment)
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.vacancies)
                    @Html.EditorFor(model => model.vacancies)
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.globalSkills)<br />
                    @Html.EditorFor(model => model.globalSkills)
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.jobRelatedSkills)<br />
                    @Html.EditorFor(model => model.jobRelatedSkills)
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.benefits)<br />
                    @Html.EditorFor(model => model.benefits)
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.requiredSkills)<br />
                    @Html.ListBoxFor(model => model.requiredSkills, new MultiSelectList(Model.AllSkills(), "Value", "Text"), new { @style = "width: 100%" })
                    @Html.ValidationMessageFor(model => model.requiredSkills)
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.promotedSkills)<br />
                    @Html.ListBoxFor(model => model.promotedSkills, new MultiSelectList(Model.AllSkills(), "Value", "Text"), new { @style = "width: 100%" })
                    @Html.ValidationMessageFor(model => model.promotedSkills)
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.studyAreas)<br />
                    @Html.ListBoxFor(model => model.studyAreas, new MultiSelectList(Model.AllStudyAreas(), "Value", "Text"), new { @style = "width: 100%" })
                    @Html.ValidationMessageFor(model => model.studyAreas)
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.studyDegrees)<br />
                    @Html.ListBoxFor(model => model.studyDegrees, new MultiSelectList(Model.AllStudyDegrees(), "Value", "Text"), new { @style = "width: 100%" })
                    @Html.ValidationMessageFor(model => model.studyDegrees)
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.languages)<br />
                    @Html.ListBoxFor(model => model.languages, new MultiSelectList(Model.AllLanguages(), "Value", "Text"), new { @style = "width: 100%" })
                    @Html.ValidationMessageFor(model => model.languages)
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.city)<br />
                    @Html.DropDownListFor(model => model.city, Model.AllCities(), new { @style = "width: 100%" })
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.institution)<br />
                    @Html.DropDownListFor(model => model.institution, Model.AllInstitutions(), new { @style = "width: 100%" })
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.host)<br />
                    @Html.DropDownListFor(model => model.host, Model.AllInstitutions(), new { @style = "width: 100%" })
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.contact)<br />
                    @Html.EditorFor(model => model.contact)
                    @Html.ValidationMessageFor(model => model.contact)
                </div>
            </div>
            <div class="col-md-4">
                <h2>Supervisor information</h2>
                <br />
                <div class="form-group">
                    @Html.LabelFor(model => model.superVisorFirstName)
                    @Html.EditorFor(model => model.superVisorFirstName)
                    @Html.ValidationMessageFor(model => model.superVisorFirstName)
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.superVisorLastName)
                    @Html.EditorFor(model => model.superVisorLastName)
                    @Html.ValidationMessageFor(model => model.superVisorLastName)
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.superVisorEmail)
                    @Html.EditorFor(model => model.superVisorEmail)
                    @Html.ValidationMessageFor(model => model.superVisorEmail)
                </div>
            </div>
        </div>
        <br />
        <div class="row">
            <div class="col-md-10 col-md-offset-1">
                <hr />
                <input type="submit" value="SAVE" class="btn btn-warning" />
            </div>
        </div>
    </div>
}

PRAXISNETWORK/PRAXISNETWORK/Views/Proposals/ProposalEdition.cshtml
@model PRAXISNETWORK.ModelViews.Proposals.Proposal

@{
    Layout = "~/Views/Shared/_Master.cshtml";
}

@section title{
    @ViewBag.Title
}

@section header{
    <script src="~/Scripts/Proposals/ProposalEditionView.js"></script>
}

@using (Html.BeginForm("SaveProposalEdition", "Proposals", FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="container">
        <div class="row">
            <div class="col-md-5 col-md-offset-1">
                <h2>Proposal information</h2>
                <br />
                <hr />
                @Html.HiddenFor(model => model.id)
                <div class="form-group">
                    @Html.LabelFor(model => model.title)
                    @Html.EditorFor(model => model.title)
                    @Html.ValidationMessageFor(model => model.title)
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.description)<br />
                    @Html.EditorFor(model => model.description)
                    @Html.ValidationMessageFor(model => model.description)
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.targets)<br />
                    @Html.ListBoxFor(model => model.targets, new MultiSelectList(Model.AllTargetsSelected(), "Value", "Text"))
                    @Html.ValidationMessageFor(model => model.targets)
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.startDate)
                    @Html.EditorFor(model => model.startDate)
                    @Html.ValidationMessageFor(model => model.startDate)
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.endDate)
                    @Html.EditorFor(model => model.endDate)
                    @Html.ValidationMessageFor(model => model.endDate)
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.validTo)
                    @Html.EditorFor(model => model.validTo)
                    @Html.ValidationMessageFor(model => model.validTo.Date)
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.payment)
                    @Html.EditorFor(model => model.payment)
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.vacancies)
                    @Html.EditorFor(model => model.vacancies)
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.globalSkills)<br />
                    @Html.EditorFor(model => model.globalSkills)
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.jobRelatedSkills)<br />
                    @Html.EditorFor(model => model.jobRelatedSkills)
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.benefits)<br />
                    @Html.EditorFor(model => model.benefits)
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.requiredSkills)<br />
                    @Html.ListBoxFor(model => model.requiredSkills, new MultiSelectList(Model.AllRequiredSkillsSelected(), "Value", "Text"), new { @style = "width: 100%" })
                    @Html.ValidationMessageFor(model => model.requiredSkills)
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.promotedSkills)<br />
                    @Html.ListBoxFor(model => model.promotedSkills, new MultiSelectList(Model.AllPromotedSkillsSelected(), "Value", "Text"), new { @style = "width: 100%" })
                    @Html.ValidationMessageFor(model => model.promotedSkills)
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.studyAreas)<br />
                    @Html.ListBoxFor(model => model.studyAreas, new MultiSelectList(Model.AllStudyAreasSelected(), "Value", "Text"), new { @style = "width: 100%" })
                    @Html.ValidationMessageFor(model => model.studyAreas)
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.studyDegrees)<br />
                    @Html.ListBoxFor(model => model.studyDegrees, new MultiSelectList(Model.AllStudyDegreesSelected(), "Value", "Text"), new { @style = "width: 100%" })
                    @Html.ValidationMessageFor(model => model.studyDegrees)
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.languages)<br />
                    @Html.ListBoxFor(model => model.languages, new MultiSelectList(Model.AllLanguagesSelected(), "Value", "Text"), new { @style = "width: 100%" })
                    @Html.ValidationMessageFor(model => model.languages)
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.city)<br />
                    @Html.DropDownListFor(model => model.city, Model.AllCitiesSelected(), new { @style = "width: 100%" })
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.institution)<br />
                    @Html.DropDownListFor(model => model.institution, Model.AllInstitutionsSelected(), new { @style = "width: 100%" })
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.host)<br />
                    @Html.DropDownListFor(model => model.host, Model.AllHostSelected(), new { @style = "width: 100%" })
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.contact)<br />
                    @Html.EditorFor(model => model.contact)
                    @Html.ValidationMessageFor(model => model.contact)
                </div>
                <hr />
            </div>
            <div class="col-md-4">
                <h2>Supervisor information</h2>
                <br />
                <div class="form-group">
                    @Html.LabelFor(model => model.superVisorFirstName)
                    @Html.EditorFor(model => model.superVisorFirstName)
                    @Html.ValidationMessageFor(model => model.superVisorFirstName)
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.superVisorLastName)
                    @Html.EditorFor(model => model.superVisorLastName)
                    @Html.ValidationMessageFor(model => model.superVisorLastName)
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.superVisorEmail)
                    @Html.EditorFor(model => model.superVisorEmail)
                    @Html.ValidationMessageFor(model => model.superVisorEmail)
                </div>
                <hr />
            </div>
        </div>
        <br />
        <div class="row">
            <div class="col-md-5 col-md-offset-1">
                <input type="submit" value="UPDATE" class="btn btn-warning" />
            </div>
        </div>
    </div>
}

PRAXISNETWORK/PRAXISNETWORK/Views/Proposals/RegisterResponse.cshtml
@{
    Layout = "~/Views/Shared/_Master.cshtml";
}

@section title{

    @ViewBag.Title
}

<div class="container-fluid">
    <div class="row">
        <div class="col-md-10 col-md-offset-1">
            <div>
                <h1>@ViewBag.Title</h1>
            </div>
            <br />
            @if (ViewBag.Success != null)
            {

                <div class="alert alert-success" role="alert">@ViewBag.Success</div>
            }
            else if (ViewBag.Error != null)
            {

                <div class="alert alert-danger" role="alert">@ViewBag.Error</div>
            }
        </div>
    </div>
</div>